#!/usr/bin/env bash
# Usage: int gitpull
# Summary: Pulls latest changes on the project with rebase.
# Help: This just runs `git pull --rebase`.
git pull --rebase
if [[ $? -ne 0 ]]
then
  echo "It seems you had some conflicts. Please fix them and try integrating again."
  exit 1
fi
