#!/usr/bin/env ruby
user = `whoami`.strip
integrating_by = `int check`.strip
if integrating_by != "" && integrating_by != user
  puts "Lock is currently set to #{integrating_by}."
  exit 1
end
if integrating_by == user
  exit
else
  system "heroku config:add INTEGRATING_BY=#{user} --app #{ENV['APP']}"
end
